import { createContext } from "react";
const SurveyListApi = createContext({
  surveyList: [{ name: null }],
  addList: () => {},
});
export default SurveyListApi;
//purPoseList: [
// { name: "상관없음", check: false },
//     { name: "캡슐", check: false },
//     { name: "정", check: false },
//     { name: "가루", check: false },
//     { name: "액상", check: false },
//     { name: "츄어블", check: false },
//     { name: "젤리", check: false },
//     { name: "포", check: false },
//     { name: "환", check: false },
//   ],
//   formationList: [
//     { name: "스트레스 케어", check: false },
//     { name: "활력 증진", check: false },
//     { name: "눈 건조감 개선", check: false },
//     { name: "관절 및 연골건장", check: false },
//     { name: "항산화", check: false },
//     { name: "시력 및 눈 피로감 케어", check: false },
//     { name: "체지방 감소", check: false },
//     { name: "면역력 감소", check: false },
//     { name: "장 건강", check: false },
//     { name: "간 건강", check: false },
//     { name: "혈압 관리", check: false },
//     { name: "혈행 개선", check: false },
//     { name: "뼈 건강", check: false },
//     { name: "콜레스테롤 수치 개선", check: false },
//     { name: "혈중 중성지질 수치 개선", check: false },
//     { name: "혈당 개선", check: false },
//     { name: "상관없음", check: false },
//   ],
